### PR TITLE
replace :before and :after with ::before and ::after

### PR DESCRIPTION
**Pull request by hippogriffic**
@incuna/frontend please review

### CODE REVIEW

**Comment by grahamgilchrist** [comment]
Looks good. Did we ever figure out whether this had any effect on browser compatibility?

**Comment by grahamgilchrist** [comment]
Double colon (`::`)is the correct way to do pseudo-elements (as opposed to the single colon for pseudo classes), but looks like it doesn't work with IE8:
https://developer.mozilla.org/en/docs/Web/CSS/Pseudo-elements

Since IE8 is still on our radar, should we consider this?
Most of this library is using CSS3 transitions which are not supported by IE8 anyway, so maybe it doesn't matter?
Will using any of the transition mixins in IE8 break styles in that browser?

**Comment by hippogriffic** [comment]
we don't seem to be supporting IE8 with new projects much any more, do you think it's likely this library will need to be used for projects that do support IE8? I'm not sure we should be add transitions to IE8 stuff anyway, and these only affect hover states so it should cause any major breakages. Progressive enhancement?

**Comment by grahamgilchrist** [comment]
Yes as you said, we shouldn't really add transitions to IE8 anyway. 

We will have less projects that need to support IE8, but there will definitely be some that will have to still support it. 

The question is, can we use this library via progressive enhancement, so that only IE10+ use it, or so that the transition selectors in the CSS don't break IE8 CSS parsing. As long as we can be sure IE8 will just ignore the selectors using double colon notation, it should be fine :)

**Comment by hippogriffic** [comment]
This https://msdn.microsoft.com/en-us/library/cc304078(v=vs.85).aspx says only :before/:after are recognised in IE8 so presumably that means ::before and ::after aren't recognised and are just ignored? Maybe?

**Comment by hippogriffic** [comment]
@grahamgilchrist after doing a bit of reading I'm still not entirely sure what the most advisable thing to do here is. I'd like to use the proper `::` pseudo as it seems like the cleanest option. I can go through all the files and add the single `:` as well, so we use both `::before` and `:before` but that's seems like a lot of work. I guess the question is do you think it's worth it in the long run? I guess we can't really know what effect these mixins will have in IE8 if the pseudo elements aren't rendered until we try it

**Comment by Minglee01** [comment]
@hippogriffic  `we don't seem to be supporting IE8 with new projects much any more`

you cant be sure that a client wont request a project for ie 8

**Comment by hippogriffic** [comment]
I don't think that's really a practical solution @Minglee01 if we think it's that important that these things work in IE8 it would be simpler just to add the single `:` in as well

**Comment by grahamgilchrist** [comment]
`:` will work in all browsers.
`::` will work in everything but not in IE8

If we needed IE8 compatibility here then I would say keep using `:`, but since this is a transition library, and transitions aren't supported until IE10, this library won't do anything in IE8 anyway, so using `::` is probably fine.

CSS rules using `::` will just be ignored by IE8, but we need to be careful when using them, as IE8 (and maybe other browsers) will ignore an entire block of rules if it doesn't understand one part of them.

For example:

```
// this would be ignored by IE8
::before
   color: red

// This would be seen correctly by IE8
.some-other-class
  color: red

// Both of these would be ignored by IE8, as the block contains a selector it doesn't understand
::before,
.some-other-class
  color: red
```

So we should be careful in our use of these to avoid grouping with other selectors, especially with things like Sass `@extends` which does that automatically.

**Comment by hippogriffic** [comment]
just did a quick scan of the files, it doesn't look like there are any places where pseudo elements are styled the same as other classes so hopefully we'll be ok, but that's good information to have thanks @grahamgilchrist :)

can this be merged then?

**Comment by grahamgilchrist** [comment]
Yes I think good to merge.

I guess more the grouping error is more to bear in mind when using it in a project. 
As long as this library is only providing Sass mixins used via `@include` rather than extensions using `@extends`, I _think_ it should be fine.

**Comment by hippogriffic** [comment]
there's definitely no `@extends` in this library, and we won't be adding anyway, I think we're trying to move away from using them in general now

**Pull request merged**
