### PR TITLE
Reconfigure library

### PR DESCRIPTION
**Pull request by hippogriffic**
you may want to review the commits separately to get a better idea of what I did. 

Essentially I removed the CSS and Less folders (and kept SCSS to convert to sass) and any other files I didn't think we needed. Then I moved everything else to a `hover` folder so we can keep it organised when we add new stuff.

There are still to dot files in the main folder that I'm not sure we need, please advise - 
https://github.com/incuna/incuna-transitions/blob/061cbfd06c704c2cc0111c1f8e92c951e3680d10/.editorconfig
https://github.com/incuna/incuna-transitions/blob/061cbfd06c704c2cc0111c1f8e92c951e3680d10/.gitignore

Next step will be converting the scss files to sass and then starting to tidy them up a bit for our use.

FYI this repo is open source for now.

@incuna/frontend please review

### CODE REVIEW

**Comment by henrahmagix** [comment]
It would be nice to have an `.editorconfig` written to match our style: indent size 4, indent style space. The rest is good and nice to have.

**Comment by henrahmagix** [comment]
I think we should keep CONTRIBUTING.md in some form. Two reasons:
1. It contains very useful tips (could go in any file).
2. An open-source repo should give advice to contributors.

**Comment by hippogriffic** [comment]
I think these are things that can be added back in a bit later. We're just getting set up right now and probably won't be looking for (or getting) much in the way of contributions, I'll add them to the confluence page

**Comment by ninjanails** [comment]
:+1:

**Pull request merged**
