### PR TITLE
put the closing } in the right place for $nameSpace variable

### PR DESCRIPTION
**Pull request by hippogriffic**
this should actually fix stuff this time.

@incuna/frontend please review

also I changed the default variable to `hover` because it's nicer than `hvr`

### CODE REVIEW

**Comment by ninjanails** [comment]
:+1:

**Comment by hippogriffic** [comment]
push the buttoooooon

**Comment by hippogriffic** [comment]
thank you :D

**Comment by ninjanails** [comment]
Your welcome :)

**Pull request merged**
