### PR TITLE
Replace custom process task with grunt-template

### PR DESCRIPTION
**Pull request by henrahmagix**
It does exactly what I wrote, so a plugin is simpler to use

For https://github.com/incuna/incuna-transitions/pull/30#discussion_r63682446

@grahamgilchrist @hippogriffic Please merge, ta!

### CODE REVIEW

**Comment by grahamgilchrist** [comment]
👍

**Comment by ninjanails** [comment]
merge conflict @henrahmagix  :(

**Comment by henrahmagix** [comment]
Woops, merged `master` instead of `page-update`. Will fix

**Comment by henrahmagix** [comment]
@incuna/frontend Fixed!

**Comment by hippogriffic** [comment]
I don't even remember seeing this ever... oops

but I guess it still looks good so eh nice job henrah

**Comment by henrahmagix** [comment]
👍

**Pull request merged**
